try:
    from .lexer import Lexer
    from .parser import Parser
except:
    from lexer import Lexer
    from parser import Parser

PULSE_CONFIG = {
    'pulse': {
        'channel': 'CH0',
        'slave_channels': {
            'AMP GATE': {
            'channel': 'CH1',
            'lead': 20e-9,
            'lag': 20e-9,
            'connectivity': 200e-9
            },
            'PROTECT': {
            'channel': 'CH2',
            'lead': 100e-9,
            'lag': 100e-9,
            'connectivity': 200e-9,
            'inverted': True
            }
        }
    },
    'acquire': {
        'channel': 'CH3'
    },
}



def compile(ast, pulse_config, parameters):
    # Placeholder for the actual compilation logic
    # This function would take the AST generated by the parser and convert it into a format suitable for execution or further processing
    compiled_output = []
    for node in ast:
        print(f"Compiling node: {node}")
    return compiled_output



if __name__ == "__main__":
    pulse_program = \
"""time tau, p1 # this is a comment
time p90
pulse 8.0ns
delay tau
pulse p1
"""
    lexer = Lexer(pulse_program)
    tokens = lexer.tokenize()
    print('Tokens:')
    for token in tokens:
        print(token)
    
    print('\nParsing Output...')
    parser = Parser(tokens)
    nodes = parser.parse()
    print('\nNodes:')
    for node in nodes:
        print(node)
    print('Done.')

    parameters = {'tau': 1e-6, 'p1': 2e-6, 'p90': 4e-6}

    print('\nCompiling...')

    out = compile(nodes, PULSE_CONFIG, parameters)
    print('Done.')