# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA_Constraints/Cmod-S7-25-Master.xdc

# IP: ip/clk_wiz_0_new/clk_wiz_0_new.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0_new || ORIG_REF_NAME==clk_wiz_0_new} -quiet] -quiet
