# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA_Constraints/Cmod-S7-25-Master.xdc

# Block Designs: bd/clock_wizard/clock_wizard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard || ORIG_REF_NAME==clock_wizard} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_clk_wiz_0_0 || ORIG_REF_NAME==clock_wizard_clk_wiz_0_0} -quiet] -quiet

# XDC: C:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.gen/sources_1/bd/clock_wizard/clock_wizard_ooc.xdc
