# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.srcs/sources_1/ip/clk_wiz_ext/clk_wiz_ext.xci
# IP: The module: 'clk_wiz_ext' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.gen/sources_1/ip/clk_wiz_ext/clk_wiz_ext_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_ext'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.gen/sources_1/ip/clk_wiz_ext/clk_wiz_ext.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_ext'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.gen/sources_1/ip/clk_wiz_ext/clk_wiz_ext_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_ext'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.srcs/sources_1/ip/clk_wiz_ext/clk_wiz_ext.xci
# IP: The module: 'clk_wiz_ext' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.gen/sources_1/ip/clk_wiz_ext/clk_wiz_ext_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_ext'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.gen/sources_1/ip/clk_wiz_ext/clk_wiz_ext.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_ext'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/jkell/Repositories/CMOD_S7_Pulse/Software/Vivado/CMOD_S7_Pulse/CMOD_S7_Pulse.gen/sources_1/ip/clk_wiz_ext/clk_wiz_ext_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_ext'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
