`timescale 1ns / 1ps

// ================================================
// Top-level module for Pulse Programmer
// ================================================
module top(
    input  wire       clk_12MHz,
    input  wire       uart_rx_pin,
    input  wire [1:0] btn,
    output wire [7:0] ja,
    output wire [3:0] led,
    output wire [2:0] led_rgb
);

    // ------------------------------------------------
    // Clock generation
    // ------------------------------------------------
    wire clk;           // 250 MHz system clock
    wire pll_locked;

    clk_wiz_0_new u_clock_wizard (
        .clk_in1  (clk_12MHz),
        .clk_out1 (clk),
        .locked   (pll_locked),
        .reset    (1'b0)          // no external reset to PLL
    );

    // ------------------------------------------------
    // External trigger (button)
    // ------------------------------------------------
    wire trig = btn[0];

    // ------------------------------------------------
    // UART Receiver + Command Shift Register
    // ------------------------------------------------
    //parameter TICKS_PER_BIT = 2170;   // for 115 200 baud @ 250 MHz
    parameter TICKS_PER_BIT = 250;   // for 1 000 000 baud @ 250 MHz    
    parameter UART_BITS     = 8;
    parameter UART_WORDS    = 10;

    wire [7:0] uart_data;
    wire       uart_rx_done;
    wire       uart_rx_busy;

    uart_rx #(.TICKS_PER_BIT(TICKS_PER_BIT)) u_uart_rx (
        .clk          (clk),
        .uart_rx_pin  (uart_rx_pin),
        .data         (uart_data),
        .uart_rx_done (uart_rx_done),
        .busy         (uart_rx_busy)
    );

    wire [(UART_BITS*UART_WORDS)-1:0] shift_reg_data;
    wire o_DV;

    inst_shift_reg #(.BITS(UART_BITS), .WORDS(UART_WORDS)) u_inst_shift_reg (
        .clk           (clk),
        .data          (uart_data),
        .i_DV          (uart_rx_done),
        .rst           (1'b0),               // usually no need to reset shift reg
        .shift_reg_data(shift_reg_data),
        .o_DV          (o_DV)
    );

    // ------------------------------------------------
    // Command decoding
    // ------------------------------------------------
    localparam [3:0] CMD_READ  = 4'b0000;
    localparam [3:0] CMD_WRITE = 4'b0001;
    localparam [3:0] CMD_START = 4'b0010;
    localparam [3:0] CMD_STOP  = 4'b0011;

    wire [3:0] COMMAND = shift_reg_data[79:76];   // assuming 80-bit shift reg

    // ------------------------------------------------
    // Dual-port RAM for pulse program
    // ------------------------------------------------
    reg  [11:0] wr_addr   = 0;
    reg         i_Wr_DV   = 0;
    reg  [63:0] i_Wr_Data = 0;
    wire [63:0] o_Rd_Data;
    wire        o_Rd_DV;      // not really used here
    
    wire [11:0] addr;           // address generated by core, very interesting that it is a wire, line position is interesting
    
    RAM_2Port #(.WIDTH(64), .DEPTH(4096)) u_RAM_2Port (
        // Write port
        .i_Wr_Clk   (clk),
        .i_Wr_Addr  (wr_addr),
        .i_Wr_DV    (i_Wr_DV),
        .i_Wr_Data  (i_Wr_Data),
        // Read port (connected directly to pulse programmer)
        .i_Rd_Clk   (clk),
        .i_Rd_Addr  (addr),      // from pulse_programmer_core
        .i_Rd_En    (1'b1),
        .o_Rd_DV    (o_Rd_DV),
        .o_Rd_Data  (o_Rd_Data)
    );

    // Extract fields for the pulse programmer
    wire [7:0]  pulse   = o_Rd_Data[63:56];
    wire [19:0] data    = o_Rd_Data[55:36];
    wire [3:0]  op_code = o_Rd_Data[35:32];
    wire [31:0] delay   = o_Rd_Data[31:0];

    // ------------------------------------------------
    // Pulse Programmer Core (new control signals)
    // ------------------------------------------------


    reg  pp_rst   = 1'b1;       // hard reset (only on power-up or emergency)
    reg  pp_start = 1'b0;       // one-cycle pulse to (re)start sequence
    reg  pp_stop  = 1'b0;       // one-cycle pulse to stop sequence
    wire pp_running;

    pulse_programmer_core u_ppc (
        .rst       (pp_rst),
        .clk       (clk),
        .start     (pp_start),   // ← new
        .stop      (pp_stop),    // ← new
        .addr      (addr),
        .op_code   (op_code),
        .delay     (delay),
        .data      (data),
        .pulse     (pulse),
        .trig      (trig),
        .pulse_out (ja),
        .running (pp_running)
    );

    // ------------------------------------------------
    // Main control process (init + UART commands)
    // ------------------------------------------------
    reg init = 1'b1;   // high during power-on memory clear

    always @(posedge clk) begin
        // Default: no write, no start/stop pulses
        if (i_Wr_DV) begin
            i_Wr_DV  <= 1'b0;
        end
        
        if (pp_start) begin
            pp_start <= 1'b0;
        end
        
        if (pp_stop) begin
            pp_stop  <= 1'b0;
        end

        if (init) begin
            // === Power-on initialization: clear BRAM to 0 ===
            i_Wr_Data <= 64'b0;
            i_Wr_DV   <= 1'b1;

            if (wr_addr == 12'd4095) begin
                wr_addr <= 12'd0;
                init    <= 1'b0;
                pp_rst  <= 1'b0;        // release hard reset after init
            end else begin
                wr_addr <= wr_addr + 1;
            end

        end else if (o_DV) begin
            // === Normal UART command handling ===
            wr_addr <= shift_reg_data[75:64];   // address for write

            case (COMMAND)
                CMD_WRITE: begin
                    i_Wr_Data <= shift_reg_data[63:0];
                    i_Wr_DV   <= 1'b1;
                end

                CMD_START: begin
                    pp_start <= 1'b1;     // one-cycle start pulse
                end

                CMD_STOP: begin
                    pp_stop <= 1'b1;      // one-cycle stop pulse
                end

                // CMD_READ or anything else: do nothing (or add read logic later)
                default: ;
            endcase
        end
    end

    // ------------------------------------------------
    // Status LEDs
    // ------------------------------------------------
    assign led[0] = pll_locked;      // PLL locked
    assign led[1] = ~pp_rst;         // core not in hard reset
    assign led[2] = uart_rx_busy;    // UART receiving
    assign led[3] = pp_running;      // spare (or use for halted status later)
    assign led_rgb[2:0] = 3'b111;    // Turns off RGB LED on board

endmodule